### ISSUE TITLE
Library Question 

### ISSUE THREAD

**Issue by rgocal** [KieronQuinn/MonetCompat#1]
I'm currently using a wallpaper change listener I forked from pixel launcher in my launcher app project, is this basically the same thing but... works?

**Comment by KieronQuinn** [comment]
An issue before the library has even properly launched, that's impressive!

It uses a wallpaper change listener internally, and automatically regenerates Monet colors for the new wallpaper, and will restart your activity to handle the change (assuming the standard setup as the wiki details). So yes, it's the same thing at its base, but with a lot on top of it.

You can compile the sample if you want to see it in action.

**Comment by rgocal** [comment]
yes, i tried building something similar for my launcher to base menus and views off the wallpaper but it wasn't very reliable so if this is a reliable option, il definitely use it or find a way to use it for what i need it todo

**Comment by KieronQuinn** [comment]
Yes, that should be possible with this library. If the default options don't automatically apply the colors to the menus & views for you, you can do it manually as detailed on the Usage wiki page

**Comment by rgocal** [comment]
oh awesome, il have to run some test and report back, thankyou for this!
