### ISSUE TITLE
Repainter and MonetCompat 

### ISSUE THREAD

**Issue by rgocal** [KieronQuinn/MonetCompat#13]
I noticed that these 2 like to show conflict and not sync. Is there a way for MonetCompat to play nice with Repainter or is it just a conflict issue.

**Comment by KieronQuinn** [comment]
I'm not sure what you mean - Repainter is not the same as MonetCompat.

Repainter applies to the system, so values from that will be used on Android 12, so long as [useSystemColorsOnAndroid12](https://github.com/KieronQuinn/MonetCompat/blob/main/library/src/main/java/com/kieronquinn/monetcompat/core/MonetCompat.kt#L77) is enabled. If it is, check that `DynamicColors.isDynamicColorAvailable()` is returning true - it's possible your device isn't showing as compatible when it in fact is (this method is in the Material library, if you find this is the case you may see some luck in simply updating that library). 

Assuming that system colours are not being used, MonetCompat will be re-calculating the palette from your wallpaper colours, which Repainter doesn't replace and so it will end up with different values.

**Comment by rgocal** [comment]
Alright, i was just curious how the two communicated (if they did at all). I noticed at times while using Repainter on my firmware, the colors suggested from monetCompat would sometimes not match the Repainter values set in the system. Maybe it was a syncing error but a reboot corrected the issue from the app not matching the returned system colors.

**Comment by KieronQuinn** [comment]
It's probably just the library not being told to update by the system, it doesn't always seem to work. It's already looking for overlay and wallpaper changes, so there's nothing I can really do about that. You could check for updates every resume I guess and check if a colour has changed, then reapply if required but that would be quite expensive.
