### ISSUE TITLE
Request: make it clearer what this library is doing, using screenshots on the main page

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [KieronQuinn/MonetCompat#3]
Took me some time to understand what it's all about, because it's written in an unclear way:

"MonetCompat is an app-level implementation of kdrag0n's custom Monet implementation, used in his android12-extensions module"

It should say that it takes the colors out of wallpapers and be able to apply them inside the app on various Views, no?

**Comment by KieronQuinn** [comment]
It could maybe be a little bit better, but does "App-level wallpaper color palette generation" not mean "it takes the colors out of wallpapers and generates a palette"?

**Comment by AndroidDeveloperLB** [comment]
@KieronQuinn But then it means it just generate colors out of wallpapers, which is something we already have (and even for very old Android versions, as part of Android-x) :
https://developer.android.com/reference/androidx/palette/graphics/Palette

and this library doesn't do just that. It actually allows to use them inside the app, like the Monet effect on Android 12, no?

**Comment by KieronQuinn** [comment]
Well yes, but Palette is not Monet. Palette extracts colors from images, but it doesn't mutate them and generate whole sets of swatches like Monet does. The whole point of this project is to backport Monet, and it kind of expects that you know what Monet is. Palette is actually used to extract the primary color(s) to feed into MonetCompat on Android 8.0 and below.

As for using it on the Views, it's up to you how/if you do that. Applying to views is not automatic, as is described in the Usage page, hence "Next, to apply Monet colors to views, check out the Usage page."

**Comment by AndroidDeveloperLB** [comment]
@KieronQuinn Still I think the current one is unclear.
Even on the small banner, it could have been "apply wallpaper colors to your app", or something like that.

Anyway please update the main page.

**Comment by KieronQuinn** [comment]
Done. You don't have to mention someone in every comment by the way, if they want to have notifications for issues they will get pinged.

**Comment by AndroidDeveloperLB** [comment]
Thank you.
The "@" is a habit, for times I forget to add it when needed.
