### ISSUE TITLE
Jetpack Compose support

### ISSUE THREAD

**Issue by rozPierog** [KieronQuinn/MonetCompat#6]
I've manage to get MonetCompat to recreate (almost) 1:1 official Jetpack compose color scheme generation
Both are with the same wallpaper
|MaterialTheme3.dynamicLightColorScheme() |MonetCompat|
|----|----|
|Android 12L|Android 10|
<img width="778" alt="image" src="https://user-images.githubusercontent.com/23499434/141303482-d43b87f1-dd11-4f18-8ab0-481586c74523.png">
<img width="778" alt="image" src="https://user-images.githubusercontent.com/23499434/141303556-f94f334d-7453-498e-b245-1f86d8d50f98.png">

Here is the implementation https://github.com/rozPierog/Cofi/blob/f8676add8d072d04ecafc082f98a6015cb25c3cc/app/src/main/java/com/omelan/cofi/ui/Theme.kt#L31

I would like to contribute this code to this repo so that everyone can use it easily.  Is it okay? Or should I create separate repo and publish it separately.

**Comment by KieronQuinn** [comment]
You are most welcome to open a PR with support, I'll merge it.

**Comment by huaweikai** [comment]
there has bug,No static method MonetCompatDynamicTheme
